### ISSUE TITLE
No module named queue

### ISSUE THREAD

**Issue by Zmash** [happyleavesaoc/python-limitlessled#5]
Hey,
thaks for the great Work.
Currently i have a problem if i try to start my programm:

`
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from limitlessled.bridge import Bridge
  File "/usr/local/lib/python2.7/dist-packages/limitlessled/bridge.py", line 3, in <module>
    import queue
ImportError: No module named queue
`

Is there a solution for this?

\Zmash

**Comment by Zmash** [comment]
Have to use python 3 instead of 2.7.
